on: ["push", "pull_request"]

name: test

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x

            - name: npm install
              run: npm install

            - name: Add prettier
              run: npm install --save-dev --save-exact prettier

            - name: Check code style
              run: prettier --config ./.prettierrc.yaml --check  ./src/*

            - name: Install jest globally
              run: npm install -g jest
            - name: Install coveralls globally
              run: npm install -g coveralls

            - name: run jest
              run: jest --coverage && coveralls < coverage/lcov.info
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
